// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewHorizon.Automation.Infrastructure.Persistence;

#nullable disable

namespace NewHorizon.Automation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AutomationDbContext))]
    [Migration("20260907084918_PoAutomationModeDefault")]
    partial class PoAutomationModeDefault
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewHorizon.Automation.Domain.Configuration.AutomationConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EnableAgent")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableModule")
                        .HasColumnType("bit");

                    b.Property<int>("ErrorRetentionDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsLicensed")
                        .HasColumnType("bit");

                    b.Property<int>("LogRetentionDays")
                        .HasColumnType("int");

                    b.Property<string>("LoggingLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ParallelWorkers")
                        .HasColumnType("int");

                    b.Property<int>("PayloadRetentionDays")
                        .HasColumnType("int");

                    b.Property<int>("PollIntervalSeconds")
                        .HasColumnType("int");

                    b.Property<int>("ReconcileIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeOnly?>("WorkingHoursEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("WorkingHoursStart")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("Module")
                        .IsUnique()
                        .HasDatabaseName("UX_AutomationConfig_Module");

                    b.ToTable("AutomationConfig", (string)null);
                });

            modelBuilder.Entity("NewHorizon.Automation.Domain.Errors.AutomationError", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiEndpoint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LaymanMessage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TechnicalMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_AutomationError_CreatedAtUtc");

                    b.HasIndex("JobId")
                        .HasDatabaseName("IX_AutomationError_JobId");

                    b.ToTable("AutomationError", (string)null);
                });

            modelBuilder.Entity("NewHorizon.Automation.Domain.Jobs.AutomationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("DurationMs")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("DATEDIFF_BIG(MILLISECOND, [StartedAtUtc], [CompletedAtUtc])");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("IndentsExamined")
                        .HasColumnType("int");

                    b.Property<int>("JobsCreated")
                        .HasColumnType("int");

                    b.Property<int?>("MaxIndents")
                        .HasColumnType("int");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("PurchaseOrdersCreated")
                        .HasColumnType("int");

                    b.Property<string>("RequestedIndentTypes")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("RequestedSites")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TriggerReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TriggerSource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TriggeredBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_AutomationRun_CorrelationId");

                    b.HasIndex("StartedAtUtc")
                        .HasDatabaseName("IX_AutomationRun_StartedAtUtc");

                    b.HasIndex("TriggerSource", "StartedAtUtc")
                        .HasDatabaseName("IX_AutomationRun_Trigger");

                    b.ToTable("AutomationRun", (string)null);
                });

            modelBuilder.Entity("NewHorizon.Automation.Domain.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CancelledBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ConversionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CurrentStage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("DurationMs")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("DATEDIFF_BIG(MILLISECOND, [StartedAtUtc], [CompletedAtUtc])");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset?>("NotBeforeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_AutomationJob_CreatedAtUtc");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("IX_AutomationJob_DocumentId");

                    b.HasIndex("RunId")
                        .HasDatabaseName("IX_AutomationJob_RunId");

                    b.HasIndex("WorkflowType")
                        .IsUnique()
                        .HasDatabaseName("UX_AutomationJob_LiveCycle")
                        .HasFilter("[DocumentType] = 'Cycle' AND [Status] <> 'Completed' AND [Status] <> 'Cancelled'");

                    b.HasIndex("ConversionId", "CreatedAtUtc")
                        .HasDatabaseName("IX_AutomationJob_Conversion");

                    b.HasIndex("Status", "Priority", "CreatedAtUtc")
                        .HasDatabaseName("IX_AutomationJob_Claim");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status", "Priority", "CreatedAtUtc"), new[] { "NotBeforeUtc" });

                    b.HasIndex(new[] { "IdempotencyKey" }, "UX_AutomationJob_IdempotencyKey_Live")
                        .IsUnique()
                        .HasDatabaseName("UX_AutomationJob_IdempotencyKey_Live")
                        .HasFilter("[Status] <> 'Cancelled' AND [ConversionId] IS NULL");

                    b.HasIndex(new[] { "IdempotencyKey" }, "UX_AutomationJob_LiveIndentConversion")
                        .IsUnique()
                        .HasDatabaseName("UX_AutomationJob_LiveIndentConversion")
                        .HasFilter("[ConversionId] IS NOT NULL AND [Status] <> 'Completed' AND [Status] <> 'Cancelled' AND [Status] <> 'Failed'");

                    b.ToTable("AutomationJob", (string)null);
                });

            modelBuilder.Entity("NewHorizon.Automation.Domain.Jobs.JobStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErpDocumentRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Target")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("UX_AutomationJobStep_Job_Sequence");

                    b.HasIndex("JobId", "Status")
                        .HasDatabaseName("IX_AutomationJobStep_Job_Status");

                    b.ToTable("AutomationJobStep", (string)null);
                });

            modelBuilder.Entity("NewHorizon.Automation.Domain.Logging.AutomationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiEndpoint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Module")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("StepId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_AutomationLog_CorrelationId");

                    b.HasIndex("JobId")
                        .HasDatabaseName("IX_AutomationLog_JobId");

                    b.HasIndex("StartedAtUtc")
                        .HasDatabaseName("IX_AutomationLog_StartedAtUtc");

                    b.ToTable("AutomationLog", (string)null);
                });

            modelBuilder.Entity("NewHorizon.Automation.Domain.Purchase.IndentPoAutomationConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DryRun")
                        .HasColumnType("bit");

                    b.Property<string>("IndentKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IndentNumbers")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastRunReference")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastRunStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("LastScheduledRunDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("LastTriggeredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MaxIndentsPerRun")
                        .HasColumnType("int");

                    b.Property<string>("RunMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeOnly?>("ScheduleTime")
                        .HasColumnType("time");

                    b.Property<string>("Sites")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IndentKind")
                        .IsUnique()
                        .HasDatabaseName("UX_IndentPoAutomationConfig_IndentKind");

                    b.ToTable("IndentPoAutomationConfig", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f1d4c20-0000-0000-0000-00000000000a"),
                            DryRun = false,
                            IndentKind = "Regular",
                            IsActive = false,
                            RunMode = "Api",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("6f1d4c20-0000-0000-0000-00000000000b"),
                            DryRun = false,
                            IndentKind = "Capital",
                            IsActive = false,
                            RunMode = "Api",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("6f1d4c20-0000-0000-0000-00000000000c"),
                            DryRun = false,
                            IndentKind = "Service",
                            IsActive = false,
                            RunMode = "Api",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("NewHorizon.Automation.Domain.Purchase.IndentPoConversion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("FirstSeenAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly?>("IndentDate")
                        .HasColumnType("date");

                    b.Property<long>("IndentId")
                        .HasColumnType("bigint");

                    b.Property<string>("IndentKind")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("IndentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IndentNumber")
                        .HasDatabaseName("IX_IndentPoConversion_IndentNumber");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("IX_IndentPoConversion_SiteId");

                    b.HasIndex("IndentKind", "IndentId")
                        .IsUnique()
                        .HasDatabaseName("UX_IndentPoConversion_Indent");

                    b.ToTable("IndentPoConversion", (string)null);
                });

            modelBuilder.Entity("NewHorizon.Automation.Domain.Purchase.IndentPoOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LineCount")
                        .HasColumnType("int");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("PoId")
                        .HasColumnType("bigint");

                    b.Property<string>("PoNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RateStructureCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<Guid?>("StepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VendorCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PoId")
                        .IsUnique()
                        .HasDatabaseName("UX_IndentPoOutcome_PoId")
                        .HasFilter("[PoId] IS NOT NULL");

                    b.HasIndex("StepId");

                    b.HasIndex("VendorCode")
                        .HasDatabaseName("IX_IndentPoOutcome_VendorCode");

                    b.HasIndex("JobId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("UX_IndentPoOutcome_Job_Sequence");

                    b.ToTable("IndentPoOutcome", null, t =>
                        {
                            t.HasCheckConstraint("CK_IndentPoOutcome_Result", "([Outcome] = 'Created' AND [PoId] IS NOT NULL AND [PoNumber] IS NOT NULL) OR ([Outcome] <> 'Created' AND [Reason] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("NewHorizon.Automation.Domain.Jobs.Job", b =>
                {
                    b.HasOne("NewHorizon.Automation.Domain.Purchase.IndentPoConversion", null)
                        .WithMany()
                        .HasForeignKey("ConversionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NewHorizon.Automation.Domain.Jobs.AutomationRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("NewHorizon.Automation.Domain.Jobs.JobStep", b =>
                {
                    b.HasOne("NewHorizon.Automation.Domain.Jobs.Job", null)
                        .WithMany("Steps")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewHorizon.Automation.Domain.Purchase.IndentPoOutcome", b =>
                {
                    b.HasOne("NewHorizon.Automation.Domain.Jobs.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewHorizon.Automation.Domain.Jobs.JobStep", null)
                        .WithMany()
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("NewHorizon.Automation.Domain.Jobs.Job", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
